/***** Do not edit this file *****/
import { Action as EnthusiasmAction } from './enthusiasm/actionTypes';
import { Action as TodoAction } from './todo/actionTypes';

export type Action = EnthusiasmAction | TodoAction;
