export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const DELAYED_INCREMENT = 'DELAYED_INCREMENT';
export type DELAYED_INCREMENT = typeof DELAYED_INCREMENT;

export const USERNAME_FETCH_SERVICE = 'USERNAME_FETCH_SERVICE';
export type USERNAME_FETCH_SERVICE = typeof USERNAME_FETCH_SERVICE;

export const USERNAME_RESPONSE_SERVICE = 'USERNAME_RESPONSE_SERVICE';
export type USERNAME_RESPONSE_SERVICE = typeof USERNAME_RESPONSE_SERVICE;
