export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const DELAYED_INCREMENT = 'DELAYED_INCREMENT';
export type DELAYED_INCREMENT = typeof DELAYED_INCREMENT;

export const FETCH_TODO = 'FETCH_TODO';
export type FETCH_TODO = typeof FETCH_TODO;

export const RESPONSE_TODO = 'RESPONSE_TODO';
export type RESPONSE_TODO = typeof RESPONSE_TODO;

export const CHANGE_PAGE_TODO = 'CHANGE_PAGE_TODO';
export type CHANGE_PAGE_TODO = typeof CHANGE_PAGE_TODO;
