/***** Do not edit this file *****/
import {
  Actions,
  IncrementEnthusiasm,
  DecrementEnthusiasm,
  DelayedIncrementEnthusiasm,
  ChangeLoading,
} from './actionTypes';
export function incrementEnthusiasm(): IncrementEnthusiasm {
  return {
    type: Actions.IncrementEnthusiasm,
  };
}
export function decrementEnthusiasm(): DecrementEnthusiasm {
  return {
    type: Actions.DecrementEnthusiasm,
  };
}
export function delayedIncrementEnthusiasm(): DelayedIncrementEnthusiasm {
  return {
    type: Actions.DelayedIncrementEnthusiasm,
  };
}
export function changeLoading(payload: boolean): ChangeLoading {
  return {
    type: Actions.ChangeLoading,
    payload,
  };
}
