/***** Do not edit this file *****/
import { Actions, FetchTodo, ResponseTodo, ChangePage } from './actionTypes';
export function fetchTodo(page: number): FetchTodo {
  return {
    type: Actions.FetchTodo,
    page,
  };
}
export function responseTodo(payload: string[], matches: number): ResponseTodo {
  return {
    type: Actions.ResponseTodo,
    payload,
    matches,
  };
}
export function changePage(): ChangePage {
  return {
    type: Actions.ChangePage,
  };
}
